### ISSUE TITLE
Support for `#[serde(crate = "path")]`

### ISSUE THREAD

**Issue by tguichaoua** [dtolnay/serde-repr#16]
I'm using [`rocket`](https://rocket.rs/) that exposes serde via the path `rocket::serde`.
To implement (de)serialize I'm using the attribute `#[serde(crate = "rocket::serde")]` to specifiy the path to serde.

**Comment by dtolnay** [comment]
I would prefer not to build this workaround into this crate.

Eventually https://github.com/rust-lang/rust/issues/54363#issuecomment-1237544924 will give a more robust way to make re-exported derive macros work without needing this kind of workaround.

In the meantime, it would be fine for someone else to maintain a more fully featured repr serde derive library that can handle this use case with an attribute.
