### ISSUE TITLE
Macro names should be CamelCase

### ISSUE THREAD

**Issue by zeenix** [dtolnay/serde-repr#22]
Perhaps there was a good reason for these to not conform to the conventions but I wanted to at least ask to see if that's the case. [rust-analyzer currently gives me warning about this](https://github.com/rust-lang/rust-analyzer/issues/15541).

If there is no objections, I can provide a PR that's backwards compatible (using type aliases)?

**Comment by dtolnay** [comment]
The rust-analyzer bug you linked is unrelated to the macro names. It's referring to something inside the generated code. Renaming the macro would not work around that bug.

**Comment by zeenix** [comment]
Sure but shouldn't we rename still for consistency with the general conventions?

**Comment by zeenix** [comment]
> Sure but shouldn't we rename still for consistency with the general conventions?

Although I do wonder if type aliases can work for attribute macros. 🤔 I've never tried it and am currently AFK.

**Comment by dtolnay** [comment]
The general convention would be that `derive(DeserializeRepr)` derives a trait called `DeserializeRepr`, which is not what this crate's macro does.

**Comment by shigma** [comment]
I believe the general convention of derive semantics has nothing to do with naming. If we just follow the "general convention", this crate should derive a trait called `Deserialize_repr`.
